##厂商目前支持阿里云短信服务(alibaba),钉钉机器人通知(dingTalk)
providers:
  alibaba:
    access_key_id: access_key_id
    access_key_secret: access_key_secret
    sign_name: sign_name
    template_code: template_code
  dingTalk:
    webhook_url: webhook_url
#************************************************************#
#接收者支持多个，多个接受者可以配置一个云厂商
receivers:
  ## name
  test1:
    provider: dingTalk
  test2:
    provider: alibaba
    to:
      - 110
  test3:
    provider: alibaba
    to:
      - 120
